style: gitlab
template: CHANGELOG.tpl.md
info:
  title: ğŸ•” å˜æ›´è®°å½•
  repository_url: https://github.com/godoes/gorm-oracle
options:
  tag_filter_pattern: '^v'
  sort: "date"
  commits:
    filters:
      Type:
        - ğŸ‰
        - âœ¨
        - ğŸš©
        - ğŸ”–
        - ğŸ©¹
        - ğŸ›
        - ğŸš‘ï¸
        - ğŸ”’ï¸
        - ğŸ”
        - ğŸš¨
        - â™»ï¸
        - ğŸ‘”
        - ğŸ±
        - ğŸ”¨
        - ğŸ”§
        - ğŸ™ˆ
        - ğŸ’¡
        - ğŸ“
        - â¬†ï¸
        - â¬‡ï¸
        - ğŸšš
        - ğŸ—ï¸
        - ğŸ‘½ï¸
        - ğŸ’¥
        - âš¡ï¸
        - ğŸš¸
        - ğŸ”Š
        - ğŸ”‡
        - ğŸ’„
        - ğŸ¨
        - ğŸ§±
        - ğŸ‘·
        - ğŸ’š
        - ğŸš€
        - ğŸ§µ
        - ğŸ›‚
        - ğŸ¦º
        - ğŸ”¥
        - ğŸ
        - ğŸ§
        - ğŸ—ƒï¸
        - ğŸ‘¥
        - ğŸ“„
        - ğŸŒ
        - âœ…
        - ğŸ§ª
        - "Merge"
  commit_groups:
    sort_by: RawTitle
    title_maps:
      ğŸ‰: åˆå§‹åŒ–
      âœ¨: æ–°ç‰¹æ€§
      ğŸš©: åŠŸèƒ½æ ‡è¯†
      ğŸ”–: ç‰ˆæœ¬å‘å¸ƒ
      ğŸ©¹: ä¿®æ”¹ä¼˜åŒ–
      ğŸ›: é—®é¢˜ä¿®å¤
      ğŸš‘ï¸: ç´§æ€¥ä¿®å¤
      ğŸ”’ï¸: å®‰å…¨ä¿®å¤
      ğŸ”: åŠ å¯†ç›¸å…³
      ğŸš¨: ä¿®å¤è­¦å‘Š
      â™»ï¸: ä»£ç é‡æ„
      ğŸ‘”: ä¸šåŠ¡é€»è¾‘
      ğŸ±: èµ„æºæ–‡ä»¶
      ğŸ”¨: å¼€å‘é…ç½®
      ğŸ”§: ç¨‹åºé…ç½®
      ğŸ™ˆ: å¿½ç•¥é…ç½®
      ğŸ’¡: æ³¨é‡Šæ–‡æ¡£
      ğŸ“: è¯´æ˜æ–‡æ¡£
      â¬†ï¸: ä¾èµ–å‡çº§
      â¬‡ï¸: ä¾èµ–é™çº§
      ğŸšš: ç§»åŠ¨æ–‡ä»¶
      ğŸ—ï¸: æ¶æ„å˜æ›´
      ğŸ‘½ï¸: å¤–éƒ¨å˜æ›´
      ğŸ’¥: çªç ´å˜æ›´
      âš¡ï¸: æ€§èƒ½ä¼˜åŒ–
      ğŸš¸: ç”¨æˆ·ä½“éªŒ
      ğŸ”Š: æ›´æ–°æ—¥å¿—
      ğŸ”‡: ç§»é™¤æ—¥å¿—
      ğŸ’„: ç•Œé¢æ ·å¼
      ğŸ¨: ä»£ç æ ¼å¼
      ğŸ§±: åŸºç¡€è®¾æ–½
      ğŸ‘·: æŒç»­é›†æˆ
      ğŸ’š: ä¿®å¤æ„å»º
      ğŸš€: éƒ¨ç½²
      ğŸ§µ: å¹¶å‘
      ğŸ›‚: æƒé™
      ğŸ¦º: éªŒè¯
      ğŸ”¥: åˆ é™¤
      ğŸ: Windows
      ğŸ§: Unix
      ğŸ—ƒï¸: æ•°æ®åº“
      ğŸ‘¥: è´¡çŒ®è€…
      ğŸ“„: è®¸å¯è¯
      ğŸŒ: å›½é™…åŒ–
      âœ…: é€šè¿‡çš„æµ‹è¯•
      ğŸ§ª: å¤±è´¥çš„æµ‹è¯•
      "Merge": åˆå¹¶
  header:
    # pattern: "^(.*)$"
    # https://regex101.com/r/wEipOM/1
    # https://emojipedia.org/emoji/%E2%9C%A8/
    pattern: "^(Merge|[\\x{1F300}-\\x{1F5FF}\\x{1F600}-\\x{1F64F}\\x{1F680}-\\x{1F6FF}\\x{1F700}-\\x{1F77F}\\x{1F780}-\\x{1F7FF}\\x{1F800}-\\x{1F8FF}\\x{1F900}-\\x{1F9FF}\\x{1FA00}-\\x{1FA6F}\\x{1FA70}-\\x{1FAFF}\\x{2600}-\\x{26FF}\\x{2700}-\\x{27BF}]|[\\x{2B05}\\x{2B06}\\x{2B07}\\x{23EA}\\x{23EB}])(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - ğŸ’¥
